language: java
sudo: true

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
    - stage: build with maven & generate reporrts
      script:
      - mvn clean verify jacoco:report coveralls:report
    - stage: build & publish docker image for server
      script:
      - mvn docker:build@build-docker -P docker-app -f ./judge-d-server/pom.xml
    - stage: build & publish docker image for agent
      script:
      - mvn docker:build@build-docker -P docker-app -f ./judge-d-agent/pom.xml
